// <auto-generated />
namespace Classfinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NoOfficial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NoOfficial));
        
        string IMigrationMetadata.Id
        {
            get { return "201307071502411_NoOfficial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
