// <auto-generated />
namespace Classfinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Unofficial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Unofficial));
        
        string IMigrationMetadata.Id
        {
            get { return "201306080413071_Unofficial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
