// <auto-generated />
namespace Classfinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class GradedClasses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GradedClasses));
        
        string IMigrationMetadata.Id
        {
            get { return "201306090542059_GradedClasses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
